apiVersion: v1
kind: Pod
metadata: 
  name: env
spec:
  containers: 
    - name: nginx
      image:  nginx
      env:
        - name: course
          value:  "devops with AWS"
        - name: tutior
          value:  "venkat damarla"
        - name: duration
          value:  "120 hours"
