apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # These labels are deployment resource labels
  labels:
    app: nginx
    tier: frontend
    purpose:  deployment
spec:
  replicas: 3
  selector:
    matchLabels:
       app: nginx
       tier: frontend
       purpose:  deployment   
  template:
    metadata:
      labels:
       app: nginx
       tier: frontend
       purpose:  deployment
    spec:
      containers:
      - name: nginx
        image: venkatdamarla/deployment:1.0
        ports:
        - containerPort: 80
